version: '3'
services:
  local-db:
    image: library/mysql:5.7
    container_name: nest_board
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: Ekdns3295@
      TZ: Asia/Seoul
    volumes:
      - ./db/mysql/data:/var/lib/mysql
      - ./db/mysql/init:/docker-entrypoint-initdb.d
    platform: linux/x86_64
  api:
    image: node:19.6.0-buster
    environment:
      MYSQL_ROOT_PASSWORD: Ekdns3295@
      TZ: Asia/Seoul
    # 컨테이너 설정시 사용할 터미널 설정
    tty: true
    ports: #hostOS 포트번호 : 도커 컨테이너 포트번호
      - '5001:5001'
    volumes: #hostOS 폴더 : 도커 컨테이너 폴더
      - .:/usr/src/app
      - /usr/src/app/node_modules
    working_dir: /app
    command: npm run start:dev
    # 의존관계 설정
